{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ include "base-microservice.namespace" . }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.name }}-secret
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.externalSecret.remoteRef }}
        property: {{ . }}
    {{- end }}
{{- end }}
