apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "base-microservice.namespace" . }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
