apiVersion: v2
name: eval
description: Instancia do chart generico para o eval-service.
type: application
version: 0.1.0
dependencies:
  - name: base-microservice
    version: 0.1.0
    repository: "file://../../charts/base-microservice"
