base-microservice:
  name: flag-service
  port: 8002

  image:
    repository: "<ECR_REGISTRY>/togglemaster/flag-service"
    tag: "v1.0.0-init"

  env:
    AUTH_SERVICE_URL: "http://auth-service.auth-service.svc.cluster.local:8001"

  ingress:
    path: /flags(/|$)(.*)

  externalSecret:
    enabled: true
    remoteRef: togglemaster/flag
    keys:
      - DATABASE_URL
